using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BrokenWheel.Control.Enum
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RPGInput
    {
        #region Main Input
        Menu = default,
        Modifier,
        Action,
        Interact,

        Debug1,
        Debug2,
        Debug3,
        Debug4,
        Debug5,
        Debug6,
        Debug7,
        Debug8,
        Debug9,
        Debug10,
        Debug11,
        Debug12,

        Inventory,
        QuickSelect,
        Map,
        Calendar,
        Journal,
        Crafting,
        Rest,

        MoveUp,
        MoveDown,
        MoveLeft,
        MoveRight,
        ToggleStance,
        ToggleSpeed,

        AttackPrimary,
        AttackSecondary,
        UseAbility,
        Reload,
        Throw,
        Kick,
        Bash,
        #endregion

        #region User Interface Input
        UIAccept,
        UISelect,
        UICancel,
        UIFocusNext,
        UIFocusPrev,
        UILeft,
        UIRight,
        UIUp,
        UIDown,
        UIPageUp,
        UIPageDown,
        UIHome,
        UIEnd,
        UICut,
        UICopy,
        UIPaste,
        UIUndo,
        UIRedo,
        UITextCompletionQuery,
        UITextCompletionAccept,
        UITextCompletionReplace,
        UITextNewline,
        UITextNewlineBlank,
        UITextNewlineAbove,
        UITextIndent,
        UITextDedent,
        UITextBackspace,
        UITextBackspaceWord,
        UITextBackspaceAllToLeft,
        UITextDelete,
        UITextDeleteWord,
        UITextDeleteAllToRight,
        UITextCaretLeft,
        UITextCaretWordLeft,
        UITextCaretRight,
        UITextCaretWordRight,
        UITextCaretUp,
        UITextCaretDown,
        UITextCaretLineStart,
        UITextCaretLineEnd,
        UITextCaretPageUp,
        UITextCaretPageDown,
        UITextCaretDocumentStart,
        UITextCaretDocumentEnd,
        UITextCaretAddBelow,
        UITextCaretAddAbove,
        UITextScrollUp,
        UITextScrollDown,
        UITextSelectAll,
        UITextSelectWordUnderCaret,
        UITextAddSelectionForNextOccurrence,
        UITextClearCaretsAndSelection,
        UITextToggleInsertMode,
        UIMenu,
        UITextSubmit,
        UIGraphDuplicate,
        UIGraphDelete,
        UIFiledialogUpOneLevel,
        UIFiledialogRefresh,
        UIFiledialogShowHidden,
        UISwapInputDirection,
        #endregion
    }
}
